from tests.database_test.database_access_test import testGetUniversalPlayerName, testGetPlayerCurrentTeam
from tests.odds_test.arbitrage_tests import sysEMainDiagonalVarsNeg1Fill_test, getArbitrageRatiosTwoLines_test, \
    checkForArbitrageAnyNumberOfLines_test

testGetPlayerCurrentTeam()
sysEMainDiagonalVarsNeg1Fill_test()
getArbitrageRatiosTwoLines_test()
checkForArbitrageAnyNumberOfLines_test()
# testGetUniversalPlayerName()